name: Main

on:
  push:
    branches: ["dev"]

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install openjdk-8-jdk maven
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout Wurm jars
        uses: actions/checkout@v4
        with:
          repository: Yoplitein/WurmJars
          path: deps
          ssh-key: ${{secrets.WURMJARS_KEY}}
      - name: Maven Build
        run: mvn install -Dclient.location="$PWD/deps"
      - name: Generate release timestamp
        run: |
          TIMESTAMP="$(date -u '+%Y-%m-%dT%H-%M-%SZ')"
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
      - name: Create tag
        run: |
          git tag ${{env.TIMESTAMP}}
          git push origin --tags
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{env.TIMESTAMP}}
          fail_on_unmatched_files: true
          files: WurmHelper.zip
